name: Secret Demo Workflow

on: [push]

jobs:
  demo_secrets_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Secret Validation
        env:
          MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          # Check if secret is set without exposing it
          if [ -n "$MY_SECRET_MESSAGE" ]; then
            echo "Secret is properly configured"
          else
            echo " Secret is not set"
            exit 1
          fi

      - name: Demo Secret Usage
        if: success()
        env:
          MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          # Example of using secret securely
          echo "🔒Using secret securely in script"
          # Simulate using secret without printing it
          echo "Secret length: ${#MY_SECRET_MESSAGE} characters"
