name: Variables Scopes Demo
# Workflow level variables
env:
  WORKFLOW_VAR: "This is set at workflow level"
  SHARED_VAR: "This comes from workflow"

on: [push]

jobs:
  # Step Level Demo
  step_level_demo:
    runs-on: ubuntu-latest
    steps:
      - name: First Step Variables
        env:
          STEP_VAR: "This is set at step 1"
          SHARED_VAR: "This comes from step 1"
        run: |
          echo "=== STEP 1 VARIABLES ==="
          echo "Step variable: $STEP_VAR"
          echo "Shared variable: $SHARED_VAR"
          echo "Workflow variable: $WORKFLOW_VAR"
          echo "========================"

      - name: Second Step Variables
        env:
          STEP_VAR: "This is set at step 2"
          SHARED_VAR: "This comes from step 2"
        run: |
          echo "=== STEP 2 VARIABLES ==="
          echo "Step variable: $STEP_VAR"
          echo "Shared variable: $SHARED_VAR"
          echo "Workflow variable: $WORKFLOW_VAR"
          echo "========================"

  # Job Level Demo
  job_level_demo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "This is set at job level"
      SHARED_VAR: "This comes from job"
    steps:
      - name: Access Job Variables
        run: |
          echo "=== JOB LEVEL VARIABLES ==="
          echo "Job variable: $JOB_VAR"
          echo "Shared variable: $SHARED_VAR"
          echo "Workflow variable: $WORKFLOW_VAR"
          echo "==========================="

      - name: Override Job Variables in Step
        env:
          SHARED_VAR: "This comes from step override"
        run: |
          echo "=== VARIABLE OVERRIDE DEMO ==="
          echo "Job variable: $JOB_VAR"
          echo "Shared variable (overridden): $SHARED_VAR"
          echo "Workflow variable: $WORKFLOW_VAR"
          echo "============================="

  # Workflow Level Demo
  workflow_level_demo:
    runs-on: ubuntu-latest
    needs: [step_level_demo, job_level_demo]
    steps:
      - name: Access Workflow Variables
        run: |
          echo "=== WORKFLOW LEVEL VARIABLES ==="
          echo "Workflow variable: $WORKFLOW_VAR"
          echo "Shared variable (from workflow): $SHARED_VAR"
          echo "================================"